### PR TITLE
fix logo on github pages

### PR DESCRIPTION
**Pull request by sahilng**
Incredibly comprehensive pull request encompassing a variety of fundamental code changes.

In other words, a shameless attempt to be Contributor 3 to this budding project.

🚀

### CODE REVIEW

**Comment by archiewood** [comment]
attempt succeeded

**Comment by archiewood** [comment]
sadly, this did not resolve the issue, more must be required

**Comment by archiewood** [comment]
got it https://github.com/archiewood/duckdb-gsheets/commit/53b6a709ea4460d4a37547d10531f1c9a3f7c086

**Comment by sahilng** [comment]
I realized that I should probably test that it works after you merged it 😄

After testing I realized that this solution was one option or can just use the raw url i.e. 
 if you want to keep your blanket exclude. Sorry for the trick PR 😅

**Pull request merged**
